site_name: OSINT Toolkit
theme:
  name: material
nav:
  - Home: OSINT-TOC.md
  - Kali Setup: kali-osint-virtualbox-setup.md
  - Resize Kali VM: resize-kali-vm.md
  - Google Dorking: google_dork_osint.md
  - OSINT Environment: OSINT_Environment_Kali_vs_Tails.md
  - theHarvester Guide: theHarvester_OSINT_Guide.md